-- =============================================================================
-- GhostNet Universal SQLite Schema
-- Compatible with: better-sqlite3 (Windows/Electron) and
--                  react-native-sqlite-storage (iOS/Android)
--
-- Design rules:
--   - All IDs are UUIDs stored as TEXT (cross-platform safe, no auto-increment)
--   - All timestamps are Unix epoch integers in milliseconds (UTC, no timezones)
--   - All message content columns store BASE64-encoded AES-256-GCM ciphertext
--   - BOOLEAN columns use INTEGER (0 = false, 1 = true) — SQLite standard
-- =============================================================================

PRAGMA journal_mode = WAL;   -- Write-Ahead Logging: safer concurrent access
PRAGMA foreign_keys = ON;    -- Enforce referential integrity


-- ---------------------------------------------------------------------------
-- TABLE: peers
-- Represents every known contact. Public keys are used for E2EE key exchange.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS peers (
    peer_id          TEXT PRIMARY KEY,   -- UUID v4 generated on first launch, shared out-of-band
    display_name     TEXT NOT NULL,      -- Locally stored nickname (never synced)
    public_key_b64   TEXT NOT NULL,      -- Base64-encoded X25519 or ECDH public key
    fingerprint      TEXT NOT NULL,      -- SHA-256 hex of the public key (for UI verification)
    first_seen_at    INTEGER NOT NULL,   -- Unix ms — when this peer was added
    last_seen_at     INTEGER,            -- Unix ms — last successful P2P connection
    is_blocked       INTEGER NOT NULL DEFAULT 0  -- 1 = blocked, messages silently dropped
);

CREATE INDEX IF NOT EXISTS idx_peers_fingerprint ON peers(fingerprint);


-- ---------------------------------------------------------------------------
-- TABLE: messages
-- Stores all inbound and outbound messages. Content is always encrypted.
-- Media files live on disk; this table stores their local path + metadata.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS messages (
    message_id          TEXT PRIMARY KEY,   -- UUID v4, generated by sender, echoed by receiver
    peer_id             TEXT NOT NULL,      -- FK → peers.peer_id (the other party in the chat)
    direction           TEXT NOT NULL CHECK(direction IN ('inbound', 'outbound')),
    type                TEXT NOT NULL CHECK(type IN ('text', 'view_once_image', 'view_once_video', 'link_preview', 'receipt')),

    -- Encrypted payload (AES-256-GCM). NULL for non-text types.
    encrypted_body      TEXT,              -- Base64(iv + authTag + ciphertext)

    -- Media (view_once_image / view_once_video). NULL for text messages.
    media_local_path    TEXT,              -- Absolute local FS path to the encrypted media file
    media_mime_type     TEXT,              -- e.g. 'image/jpeg', 'video/mp4'
    media_size_bytes    INTEGER,           -- Original plaintext file size

    -- View-once controls
    is_view_once        INTEGER NOT NULL DEFAULT 0,  -- 1 = must be deleted after first view
    is_viewed           INTEGER NOT NULL DEFAULT 0,  -- 1 = recipient has opened it
    viewed_at           INTEGER,                     -- Unix ms when viewed

    -- Link preview FK
    link_metadata_id    TEXT,              -- FK → link_metadata.id (nullable)

    -- Anti-screenshot flag: instructs the UI layer to apply secure rendering
    screenshot_protected INTEGER NOT NULL DEFAULT 0,

    -- Lifecycle timestamps
    sent_at             INTEGER NOT NULL,  -- Unix ms — when the sender created the message
    received_at         INTEGER,           -- Unix ms — when this device received it (inbound only)
    expires_at          INTEGER NOT NULL,  -- Unix ms — purge deadline (typically sent_at + 43200000)

    -- Delivery/read state
    status              TEXT NOT NULL DEFAULT 'pending'
                        CHECK(status IN ('pending', 'sent', 'delivered', 'read', 'failed', 'purged')),

    FOREIGN KEY (peer_id)          REFERENCES peers(peer_id)          ON DELETE CASCADE,
    FOREIGN KEY (link_metadata_id) REFERENCES link_metadata(id)       ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_messages_peer_id   ON messages(peer_id);
CREATE INDEX IF NOT EXISTS idx_messages_expires_at ON messages(expires_at);
CREATE INDEX IF NOT EXISTS idx_messages_status     ON messages(status);
CREATE INDEX IF NOT EXISTS idx_messages_type       ON messages(type);


-- ---------------------------------------------------------------------------
-- TABLE: link_metadata
-- Locally cached OpenGraph data fetched via the secure proxy function.
-- Never fetched by the recipient's device to avoid IP leakage.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS link_metadata (
    id              TEXT PRIMARY KEY,    -- UUID v4
    original_url    TEXT NOT NULL,       -- The raw URL shared in the message
    canonical_url   TEXT,               -- og:url (may differ from original)
    title           TEXT,               -- og:title (stored as plaintext for display)
    description     TEXT,               -- og:description
    thumbnail_path  TEXT,               -- Local path to cached thumbnail image
    site_name       TEXT,               -- og:site_name (e.g. "Instagram", "TikTok")
    fetched_at      INTEGER NOT NULL,   -- Unix ms — used to expire stale previews
    fetch_error     TEXT                -- Error message if fetch failed (NULL = success)
);

CREATE INDEX IF NOT EXISTS idx_link_metadata_url ON link_metadata(original_url);
